package by.htp.ex.controller;

public enum CommandName {
	GO_TO_BASE_PAGE, GO_TO_AUTHORIZATION_PAGE, GO_TO_REGISTRATION_PAGE,
	GO_TO_NEWS_LIST, GO_TO_VIEW_NEWS, GO_TO_USER_PROFILE, GO_TO_EDIT_USER_PROFILE,
	
	DO_REGISTRATION, DO_AUTHORIZATION, DO_SIGN_OUT, DO_UPDATE_USER, 
	
	UNDEFINED, 
}
