package by.htp.ex.controller;

public enum CommandName {
	GO_TO_BASE_PAGE, GO_TO_AUTHORIZATION_PAGE, GO_TO_REGISTRATION_PAGE,
	GO_TO_NEWS_LIST, GO_TO_VIEW_NEWS,
	
	DO_REGISTRATION, DO_AUTHORIZATION, DO_SIGN_OUT, UNDEFINED, 
}
